version: "3.7"

services:
  receiver:
    build: "./receiver"
    restart: always
    links:
      - mq

  publisher:
    build: "./publisher" 
    restart: always
    links:
      - mq
    ports:
      - 5000:5000

  mq:
    image: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports: 
      - 5671:5671
      - 5672:5672  
