version: "3.7"

services:
  mq-server:
    image: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports: 
      - 5671:5671
      - 5672:5672

  receiver:
    build: "./receiver"
    restart: always
    links:
      - mq-server

  publisher:
    build: "./publisher" 
    restart: always
    links:
      - mq-server 
