#!/bin/bash
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 1" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 2" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 3" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 4" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 5" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 6" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 7" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 8" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 9" }' -H 'Content-Type: application/json'
 curl -X POST -i http://localhost:5000/publish -d '{ "queueName": "filona-da-hora", "message": "msg do Wolgrand 10" }' -H 'Content-Type: application/json'